name: Overwrite commands

on:
    push:
        branches: [main]
        paths:
            - 'src/discord/commands/**'
    workflow_dispatch:

jobs:
    commands:
        name: Overwrite commands to Discord
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn.lock
                  cache-dependency-path: yarn.lock

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run script
              env:
                  DISCORD_BOT_AUTH: ${{ secrets.DISCORD_BOT_AUTH }}
                  DISCORD_BOT_STAGING_AUTH: ${{ secrets.DISCORD_BOT_STAGING_AUTH }}
              run: yarn script:commands prod dev
