name: Overwrite guild bot commands

on:
    push:
        branches: [main]
        paths:
            - 'src/discord/commands'
    workflow_dispatch:

jobs:
    commands:
        name: Execute
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn.lock
                  cache-dependency-path: yarn.lock

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run script
              run: yarn script:commands prod dev
